repos:
  - repo: local
    hooks:
      - id: standard-readme
        name: standard-readme
        language: node
        entry: ./dist/index.js
        files: ^README\.md$
        additional_dependencies:
          - standard-readme
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.1
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json, toml, typescript]
